/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/Button.vue')['default']
    BaseIcon: typeof import('./components/base/Icon.vue')['default']
    BaseMenu: typeof import('./components/base/Menu.vue')['default']
    BaseModal: typeof import('./components/base/Modal.vue')['default']
    LayoutCart: typeof import('./components/layout/Cart.vue')['default']
    LayoutFooter: typeof import('./components/layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/layout/Header.vue')['default']
    LayoutProductCard: typeof import('./components/layout/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
