/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/Button.vue')['default']
    BaseIcon: typeof import('./components/base/Icon.vue')['default']
    BaseSelect: typeof import('./components/base/Select.vue')['default']
    LayoutCart: typeof import('./components/layout/Cart.vue')['default']
    LayoutHeader: typeof import('./components/layout/Header.vue')['default']
    LayoutMobileMenu: typeof import('./components/layout/MobileMenu.vue')['default']
    LayoutProductCard: typeof import('./components/layout/ProductCard.vue')['default']
    LayoutSearchPreview: typeof import('./components/layout/SearchPreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
